database: "survival"

messages:
  prefix: "&3&lWarps: &7"

economy:
  create: 5000

guide:
  title: "Warps Guide"
  author: "Firestarter Staff"
  pages:
    - "§2Coming soon™"
    - "§c*no really, it is coming soon*"