database: "survival"

messages:
  prefix: "&3&lWarps: &7"

economy:
  create: 5000

categories:
  All: BOOK
  Shop: CHEST
  Utility: ENDER_CHEST
  Grinder: EXPERIENCE_BOTTLE
  PvP: GOLDEN_SWORD
  Attraction: FIREWORK_ROCKET
  Town: ORANGE_BED

guide:
  title: "Warps Guide"
  author: "Firestarter Staff"
  pages:
    - "§2Coming soon™"
    - "§c*no really, it is coming soon*"