name: Phase
version: 2.0
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Phase.Phase
description: A dead simple and hyper efficient warp system.
website: https://github.com/firestartermc/Phase
api-version: 1.15
depend: ['Kerosene', 'Essentials', 'Vault']

commands:
  warp:
    usage: "/<command> <warp>"
    description: "View the warp GUI or teleport to a warp."
    aliases: ['warps', 'go']
  setwarp:
    usage: "/<command> <name>"
    description: "Set a warp at your current location."
    aliases: ['createwarp', 'newwarp', 'addwarp']
  warpadmin:
    usage: "/<command> <operation>"
    description: "Manage the warps system in-game."